name: Unit Testing by PyTest
on: push
jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Unit Testing by PyTest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          cd app
          uvicorn main:app --host 0.0.0.0 --port 8000
          

      - name: Run tests
        run: |
          pytest
